### ISSUE TITLE
With a fresh install from pip on my VPS, attempting to run mlt with the Python training data throws numpy errors and halts.

### ISSUE THREAD

**Issue by hvanbin** [jankrepl/mltype#105]
### Environment

- VPS (Vultr)
- Arch Linux (rolling)
- pip (23.0.1) from /usr/lib/python3.10/site-packages/pip (python 3.10)
- **numpy (1.24.2)**
- mltype (0.2)

### Steps to Reproduce

PATH="${PATH}:${HOME}/.local/bin" # in case this is not added
export PATH
pip install mltype
pip train \<PATH\> # Download Python language from https://drive.google.com/file/d/14W-Ymi-h6jqNyqM5yGXyzwG25J3zzdn3/view?usp=sharing
mlt sample python

### Expected Result

`mlt sample python` should save off the terminal buffer and start interaction.

### Actual Result

`mlt sample python` raises a numpy error.

### Proof

```
Traceback (most recent call last):
  File "/home/hvanb/.local/bin/mlt", line 8, in <module>
    sys.exit(cli())
  File "/home/hvanb/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/hvanb/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/hvanb/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hvanb/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hvanb/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/hvanb/.local/lib/python3.10/site-packages/mltype/cli.py", line 658, in sample
    text = sample_text(
  File "/home/hvanb/.local/lib/python3.10/site-packages/mltype/ml.py", line 283, in sample_text
    new_ch, h, c = sample_char(
  File "/home/hvanb/.local/lib/python3.10/site-packages/mltype/ml.py", line 198, in sample_char
    features = np.zeros((1, len(vocabulary)), dtype=np.bool)
  File "/home/hvanb/.local/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
 ```

### Work Around

`pip install numpy==1.23.1`
```
Defaulting to user installation because normal site-packages is not writeable
Collecting numpy==1.23.1
  Downloading numpy-1.23.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 95.1 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.2
    Uninstalling numpy-1.24.2:
      Successfully uninstalled numpy-1.24.2
Successfully installed numpy-1.23.1
```
`mlt sample python`

**Comment by jankrepl** [comment]
Addressed in #107
