### ISSUE TITLE
Getting error during the installation

### ISSUE THREAD

**Issue by BexTuychiev** [jankrepl/mltype#88]
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\User\anaconda3\envs\type_practice\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Te
mp\\pip-install-l4o242vy\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-l4o242vy\\torch\\setup.py'"'"';f=getattr(tokenize,
 '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Us
ers\User\AppData\Local\Temp\pip-wheel-sxy5o8dr'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-l4o242vy\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\User\AppData\Local\Temp\pip-install-l4o242vy\torch\setup.py", line 225, in <module>
      setup(name="torch", version="0.1.2.post2",
    File "C:\Users\User\anaconda3\envs\type_practice\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\User\anaconda3\envs\type_practice\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\User\AppData\Local\Temp\pip-install-l4o242vy\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\User\anaconda3\envs\type_practice\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Te
mp\\pip-install-l4o242vy\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-l4o242vy\\torch\\setup.py'"'"';f=getattr(tokenize,
 '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-l4o242vy\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
Installing collected packages: torch, six, grpcio, absl-py, markdown, tensorboard-plugin-wit, pyasn1, rsa, pyasn1-modules, cachetools, google-auth, idna, urllib3,
chardet, requests, oauthlib, requests-oauthlib, google-auth-oauthlib, protobuf, werkzeug, tensorboard, fsspec, tqdm, future, pytorch-lightning, mltype
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\User\anaconda3\envs\type_practice\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\
Temp\\pip-install-l4o242vy\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-l4o242vy\\torch\\setup.py'"'"';f=getattr(tokeniz
e, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C
:\Users\User\AppData\Local\Temp\pip-record-qtk_rl3e\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\User\anaconda3\en
vs\type_practice\Include\torch'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-l4o242vy\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-l4o242vy\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "C:\Users\User\anaconda3\envs\type_practice\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\User\AppData\Local\Temp\pip-install-l4o242vy\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\User\anaconda3\envs\type_practice\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\User\AppData\Local\Temp\pip-install-l4o242vy\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
I am getting this error when I try to install it. I tried both with cloning the repo and also with `pip`. Not working
ERROR: Command errored out with exit status 1: 'C:\Users\User\anaconda3\envs\type_practice\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'
C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-l4o242vy\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-l4o242vy\\torch
\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"
'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-qtk_rl3e\install-record.txt' --single-version-externally-managed --compile --install-he
aders 'C:\Users\User\anaconda3\envs\type_practice\Include\torch' Check the logs for full command output.

**Comment by jankrepl** [comment]
Hey there,
I think this SO thread is about your problem
https://stackoverflow.com/questions/56859803/modulenotfounderror-no-module-named-tools-nnwrap

Try some of the proposed solutions and feel free to post an update here.

**Comment by BexTuychiev** [comment]
That helped thanks!
