### ISSUE TITLE
Sampling / training failure

### ISSUE THREAD

**Issue by bohdan-huma** [jankrepl/mltype#99]
Hi there. I have an issue with the sampling and training.

Sampling steps with pretrained:
1. Downloaded .zip archive from https://github.com/raywenderlich/swift-algorithm-club
2. put it into .mltype/languages
3. run ```mlt sample swift.zip```
4. Get this 
```
Traceback (most recent call last):
  File "/usr/local/bin/mlt", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mltype/cli.py", line 575, in sample
    network, vocabulary = load_model(model_folder)
  File "/usr/local/lib/python3.9/site-packages/mltype/ml.py", line 839, in load_model
    output_dict = torch.load(path, map_location=torch.device("cpu"))
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: Expected hasRecord("version") to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

Training steps:
0. having some random `*.txt` file
1. run `mlt train sometext.txt my_model`
2. get this
```
============================ Parameters | 10:17:48 =============================
{'batch_size': 64,
 'checkpoint_path': None,
 'dense_size': 128,
 'early_stopping': False,
 'extensions': None,
 'fill_strategy': 'skip',
 'gpus': None,
 'hidden_size': 32,
 'illegal_chars': None,
 'max_epochs': 10,
 'model_name': 'my_model',
 'n_layers': 1,
 'output_path': None,
 'path': ('sometext.txt',),
 'train_test_split': 0.9,
 'use_mlflow': False,
 'vocab_size': 50,
 'window_size': 50}
========================== Reading file(s) | 10:17:48 ==========================
BinarySearch.txt
======================= Computing vocabulary | 10:17:48 ========================
# characters: 50
[' ', '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', ':', '<', '=', '>', '?', 'B', 'C', 'I', 'N', 'S', 'T', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', '{', '}']
======================= Creating training set | 10:17:48 =======================
100%|████████████████████████████████████████████| 1/1 [00:00<00:00, 167.42it/s]
X.dtype=int8, y.dtype=int8
Train: 424
Validation: 48
Traceback (most recent call last):
  File "/usr/local/bin/mlt", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mltype/cli.py", line 326, in train
    run_train(
  File "/usr/local/lib/python3.9/site-packages/mltype/ml.py", line 762, in run_train
    chp_callback = pl.callbacks.ModelCheckpoint(
TypeError: __init__() got an unexpected keyword argument 'filepath'
```

**Comment by jankrepl** [comment]
@bohdan-huma Thank you for the interest.

Regarding the sampling part, it seems like you just downloaded the zipped source code, right? If that is the case this is not how `mltype sample` works. It expects a pretrained model.


Regarding the training, could you please share what `pip freeze` gives in your environment. And also the Python version you are using.


Thank you in advance

**Comment by bohdan-huma** [comment]
@jankrepl thanks for a quick response
```python -V``` gives me ```Python 3.9.4```

and here's the result of a ```pip freeze``` run
```
absl-py==1.0.0
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
bcrypt==3.2.0
cachetools==5.0.0
certifi==2021.5.30
cffi==1.15.0
charset-normalizer==2.0.4
click==8.0.4
cryptography==36.0.2
cycler==0.11.0
distro==1.7.0
docker==5.0.3
docker-compose==1.29.2
docker-compost==0.1
dockerpty==0.4.1
docopt==0.6.2
fonttools==4.31.1
frozenlist==1.3.0
fsspec==2022.2.0
future==0.18.2
google-auth==2.6.2
google-auth-oauthlib==0.4.6
grpcio==1.44.0
idna==3.2
importlib-metadata==4.11.3
jsonschema==3.2.0
kiwisolver==1.4.0
Markdown==3.3.6
matplotlib==3.5.1
mltype==0.1.1
multidict==6.0.2
networkx==2.7.1
numpy==1.22.3
oauthlib==3.2.0
packaging==21.3
paramiko==2.10.3
Pillow==9.0.1
protobuf==3.19.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pyDeprecate==0.3.1
PyNaCl==1.5.0
pyparsing==3.0.7
pyrsistent==0.18.1
python-dateutil==2.8.2
python-dotenv==0.19.2
pytorch-lightning==1.5.10
PyYAML==5.4.1
requests==2.26.0
requests-oauthlib==1.3.1
rsa==4.8
six==1.16.0
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
texttable==1.6.4
torch==1.11.0
torchmetrics==0.7.2
tqdm==4.63.0
typing_extensions==4.1.1
urllib3==1.26.6
websocket-client==0.59.0
Werkzeug==2.0.3
yarl==1.7.2
zipp==3.7.0
```

**Comment by jankrepl** [comment]
@bohdan-huma I created a PR  #101 where I try to investigate and fix the issue (still work in progress).

The CI is actually failing. It wasn't run for more than a year so it is a good thing you noticed something is not right:) Thank you again for reporting the issue.


Anyway, the problem is most likely coming from `pytorch-lightning` and its major release 1. Run the following for a quick fix that made the CI pass on my machine.
```
pip install "pytorch-lightning<1"
```

**Comment by bohdan-huma** [comment]
@jankrepl this does not seem to fix the issue

still getting the same error when run `mlt sample swift.zip`

`pip freeze` shows `pytorch-lightning==0.10.0` now

**Comment by jankrepl** [comment]
> @jankrepl this does not seem to fix the issue
> 
> still getting the same error when run `mlt sample swift.zip`
> 
> `pip freeze` shows `pytorch-lightning==0.10.0` now

Ok! Well, I will try to work on it ASAP and I will update you once there are any updates:)

**Comment by bohdan-huma** [comment]
@jankrepl  thank you!

**Comment by jankrepl** [comment]
@bohdan-huma I restricted the `pytorch-lightning` version both from above and below. Locally, I am able to do both `mlt sample` and `mlt train` and the CI passes.

Could you just quickly check whether it works for you too? You can run the command below (clones and checks out the branch with the fix and then installs)
```
pip install git+ssh://git@github.com/jankrepl/mltype.git@fix-keyword-issue
```

**Comment by bohdan-huma** [comment]
@jankrepl 
that seem to have fixed the issue!
the `pip freeze` gives `pytorch-lightning==1.1.8` now 

`train` works as expected, `sapmle` only works with models, not with the `.zip` files

but that's enough, I now started training from folder from that zip file
thank you!

**Comment by jankrepl** [comment]
>  sample only works with models, not with the .zip files, meaning that mlt sample swift.zip does not work, throwing the same error as previously
I am still not sure where your `swift.zip` comes from. When you open the google drive link (taken from README https://drive.google.com/file/d/1f6TQQL7lvWRlq7t17B0qn-fN0CRZU71h/view) and then click on download it downloads a file without any extension named `swift`. At least that is the behavior on my Mac. Are you on windows?

Anyway, I am glad we managed to make it work:) If you don't have any other requests I am going to merge the PR and release a new version on PyPI.
